# Generated by Django 4.0.5 on 2022-06-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_attendances'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendances',
            table='attendances',
        ),
        migrations.AlterModelTable(
            name='block_requirements',
            table='block_requirements',
        ),
        migrations.AlterModelTable(
            name='shifts',
            table='shifts',
        ),
        migrations.AlterModelTable(
            name='timetable_details',
            table='timetable_details',
        ),
        migrations.AlterModelTable(
            name='timetable_requirements',
            table='timetable_requirements',
        ),
        migrations.AlterModelTable(
            name='timetables',
            table='timetables',
        ),
    ]
