# Generated by Django 4.0.5 on 2022-06-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room_bookings',
            table='room_bookings',
        ),
        migrations.AlterModelTable(
            name='rooms',
            table='rooms',
        ),
    ]
