# Generated by Django 4.0.5 on 2022-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_bookings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
