# Generated by Django 4.0.5 on 2022-06-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0002_semesters_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='semesters',
            table='semesters',
        ),
    ]
