# Generated by Django 4.0.5 on 2022-06-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profiles_table_alter_roles_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.roles'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='role',
            field=models.IntegerField(null=True),
        ),
    ]
