# Generated by Django 4.0.5 on 2022-06-26 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.roles'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.IntegerField(null=True),
        ),
    ]
